conditionSpidOnt = "CTRL_C to break"
condition = "-----------------------------------------------------------------------------"
spidHeader = "SPID,ID,ATT,PORT_TYPE,F/S,/P,VPI,VCI,FLOW_TYPE,FLOW_PARA,RX,TX,STATE,"
conditionSPID = """Next valid free service virtual port ID: """
spidCheck = {
    "index": "Index               : ",
    "id": "VLAN ID             : ",
    "attr": "VLAN attr           : ",
    "endAttr": "Port type",
    "plan": "Outbound table name : ",
    "adminStatus": "Admin status        : ",
    "status": "State               : ",
    "endStatus": "Label               :",
}

planX2Maps = {
    "7": "OZ_FAMILY",
    "8": "OZ_DEDICADO-10",
    "9": "OZ_START",
    "15": "OZ_FAMILY",
    "16": "OZ_DEDICADO-5",
    "18": "UNLIMITED",
    "19": "OZ_VOIP",
    "30": "OZ_MAX",
    "32": "OZ_MAGICAL",
    "33": "OZ_NEXT",
    "34": "OZ_LIFT",
    "36": "OZ_UP",
    "44": "OZ_EMPRENDE",
    "45": "OZ_INICIATE",
    "46": "OZ_CONECTA",
    "47": "OZ_SKY",
    "48": "OZ_MAX",
    "49": "OZ_PLUS",
    "50": "OZ_DEDICADO-10-2",
}
planX15NMaps = {
    "210": "OZ_0",
    "211": "OZ_PLUS",
    "212": "OZ_MAX",
    "213": "OZ_NEXT",
    "214": "OZ_MAGICAL",
    "215": "OZ_SKY",
    "310": "OZ_0_IP",
    "311": "OZ_PLUS_IP",
    "312": "OZ_MAX_IP",
    "313": "OZ_NEXT_IP",
    "314": "OZ_MAGICAL_IP",
    "315": "OZ_SKY_IP",
}
planX15Maps = {
    "6": "OZ_LIFT",
    "7": "OZ_FAMILY",
    "9": "OZ_VOIP",
    "11": "OZ_DEDICADO_150",
    "15": "UNLIMITED",
    "16": "OZ_DEDICADO-10",
    "20": "OZ_DEDICADO-5",
    "23": "OZ_START",
    "25": "OZ_FAMILY",
    "39": "OZ_MAGICAL",
    "40": "OZ_NEXT",
    "41": "OZ EMPRENDE",
    "42": "OZ_EMPRENDE",
    "43": "OZ_INICIATE",
    "44": "OZ_CONECTA",
    "45": "OZ_SKY",
    "46": "OZ_MAX",
    "47": "OZ_PLUS",
    "48": "OZ_DEDICADO-10-2",
    "49": "OZ_UP",
}



###########	OLD      ###########
PLANS = {
    "1": {
        "OZ_0_1": {
            "line_profile": 3,
            "srv_profile": 210,
            "vlan": 3100,
            "provider": "INTER",
            "name": "OZ_0_1",
            "plan": 210,
            "gem_port": 20
        },
        "OZ_PLUS_1": {
            "line_profile": 17,
            "srv_profile": 211,
            "vlan": 3101,
            "name": "OZ_PLUS_1",
            "provider": "INTER",
            "plan": 211,
            "gem_port": 21
        },
        "OZ_MAX_1": {
            "line_profile": 27,
            "srv_profile": 212,
            "vlan": 3102,
            "name": "OZ_MAX_1",
            "provider": "INTER",
            "plan": 212,
            "gem_port": 22
        },
        "OZ_NEXT_1": {
            "line_profile": 37,
            "srv_profile": 213,
            "vlan": 3103,
            "name": "OZ_NEXT_1",
            "provider": "INTER",
            "plan": 213,
            "gem_port": 23
        },
        "OZ_MAGICAL_1": {
            "line_profile": 47,
            "srv_profile": 214,
            "vlan": 3104,
            "name": "OZ_MAGICAL_1",
            "provider": "INTER",
            "plan": 214,
            "gem_port": 24
        },
        "OZ_SKY_1": {
            "line_profile": 57,
            "srv_profile": 215,
            "vlan": 3105,
            "name": "OZ_SKY_1",
            "provider": "INTER",
            "plan": 215,
            "gem_port": 25
        },
        "OZ_0_2": {
            "line_profile": 3,
            "srv_profile": 210,
            "vlan": 2100,
            "provider": "VNET",
            "name": "OZ_0_2",
            "plan": 210,
            "gem_port": 20
        },
        "OZ_PLUS_2": {
            "line_profile": 17,
            "srv_profile": 211,
            "vlan": 2101,
            "name": "OZ_PLUS_2",
            "provider": "VNET",
            "plan": 211,
            "gem_port": 21
        },
        "OZ_MAX_2": {
            "line_profile": 27,
            "srv_profile": 212,
            "vlan": 2102,
            "name": "OZ_MAX_2",
            "provider": "VNET",
            "plan": 212,
            "gem_port": 22
        },
        "OZ_NEXT_2": {
            "line_profile": 37,
            "srv_profile": 213,
            "vlan": 2103,
            "name": "OZ_NEXT_2",
            "provider": "VNET",
            "plan": 213,
            "gem_port": 23
        },
        "OZ_MAGICAL_2": {
            "line_profile": 47,
            "srv_profile": 214,
            "vlan": 2104,
            "name": "OZ_MAGICAL_2",
            "provider": "VNET",
            "plan": 214,
            "gem_port": 24
        },
        "OZ_SKY_2": {
            "line_profile": 57,
            "srv_profile": 215,
            "vlan": 2105,
            "name": "OZ_SKY_2",
            "provider": "VNET",
            "plan": 215,
            "gem_port": 25
        },
        "OZ_PLUS_IP": {
            "line_profile": 18,
            "srv_profile": 311,
            "vlan": 102,
            "provider": "PUBLICAS",
            "name": "OZ_PLUS_IP",
            "plan": 311,
            "gem_port": 14
        },
        "OZ_MAX_IP": {
            "line_profile": 28,
            "srv_profile": 312,
            "vlan": 102,
            "provider": "PUBLICAS",
            "name": "OZ_MAX_IP",
            "plan": 312,
            "gem_port": 14
        },
        "OZ_NEXT_IP": {
            "line_profile": 38,
            "srv_profile": 313,
            "vlan": 102,
            "provider": "PUBLICAS",
            "name": "OZ_NEXT_IP",
            "plan": 313,
            "gem_port": 14
        },
        "OZ_MAGICAL_IP": {
            "line_profile": 48,
            "srv_profile": 314,
            "vlan": 102,
            "provider": "PUBLICAS",
            "name": "OZ_MAGICAL_IP",
            "plan": 314,
            "gem_port": 14
        },
        "OZ_SKY_IP": {
            "line_profile": 58,
            "srv_profile": 315,
            "vlan": 102,
            "provider": "PUBLICAS",
            "name": "OZ_SKY_IP",
            "plan": 315,
            "gem_port": 14
        },
    },
    "2": {
        "OZ_PLUS_1": {
            "line_profile": 2,
            "srv_profile": 2,
            "vlan": 1101,
            "name": "OZ_PLUS_1",
            "provider": "INTER",
            "plan": 47,
            "gem_port": 14
        },
        "OZ_MAX_1": {
            "line_profile": 2,
            "srv_profile": 2,
            "vlan": 1101,
            "provider": "INTER",
            "name": "OZ_MAX_1",
            "plan": 46,
            "gem_port": 14
        },
        "OZ_NEXT_1": {
            "line_profile": 2,
            "srv_profile": 2,
            "vlan": 1101,
            "provider": "INTER",
            "name": "OZ_NEXT_1",
            "plan": 40,
            "gem_port": 14
        },
        "OZ_MAGICAL_1": {
            "line_profile": 2,
            "srv_profile": 2,
            "vlan": 1101,
            "provider": "INTER",
            "name": "OZ_MAGICAL_1",
            "plan": 39,
            "gem_port": 14
        },
        "OZ_SKY_1": {
            "line_profile": 2,
            "srv_profile": 2,
            "vlan": 1101,
            "provider": "INTER",
            "name": "OZ_SKY_1",
            "plan": 45,
            "gem_port": 14
        },
        "OZ_START_1": {
            "line_profile": 2,
            "srv_profile": 2,
            "vlan": 1101,
            "provider": "INTER",
            "name": "OZ_START_1",
            "plan": 23,
            "gem_port": 14
        },
        "OZ_FAMILY_1": {
            "line_profile": 2,
            "srv_profile": 2,
            "vlan": 1101,
            "provider": "INTER",
            "name": "OZ_FAMILY_1",
            "plan": 25,
            "gem_port": 14
        },
        "OZ_EMPRENDE_1": {
            "line_profile": 2,
            "srv_profile": 2,
            "vlan": 1101,
            "provider": "INTER",
            "name": "OZ_EMPRENDE_1",
            "plan": 42,
            "gem_port": 14
        },
        "OZ_CONECTA_1": {
            "line_profile": 2,
            "srv_profile": 2,
            "vlan": 1101,
            "provider": "INTER",
            "name": "OZ_CONECTA_1",
            "plan": 44,
            "gem_port": 14
        },
        "OZ_INICIATE_1": {
            "line_profile": 2,
            "srv_profile": 2,
            "vlan": 1101,
            "provider": "INTER",
            "name": "OZ_INICIATE_1",
            "plan": 43,
            "gem_port": 14
        },
        "OZ_LIFT_1": {
            "line_profile": 2,
            "srv_profile": 2,
            "vlan": 1101,
            "provider": "INTER",
            "name": "OZ_LIFT_1",
            "plan": 6,
            "gem_port": 14
        },
        "OZ_UP_1": {
            "line_profile": 2,
            "srv_profile": 2,
            "vlan": 1101,
            "provider": "INTER",
            "name": "OZ_UP_1",
            "plan": 49,
            "gem_port": 14
        },
        "OZ_PLUS_2": {
            "line_profile": 2,
            "srv_profile": 2,
            "vlan": 1102,
            "provider": "VNET",
            "name": "OZ_PLUS_2",
            "plan": 47,
            "gem_port": 14
        },
        "OZ_MAX_2": {
            "line_profile": 2,
            "srv_profile": 2,
            "vlan": 1102,
            "provider": "VNET",
            "name": "OZ_MAX_2",
            "plan": 46,
            "gem_port": 14
        },
        "OZ_NEXT_2": {
            "line_profile": 2,
            "srv_profile": 2,
            "vlan": 1102,
            "provider": "VNET",
            "name": "OZ_NEXT_2",
            "plan": 40,
            "gem_port": 14
        },
        "OZ_MAGICAL_2": {
            "line_profile": 2,
            "srv_profile": 2,
            "vlan": 1102,
            "provider": "VNET",
            "name": "OZ_MAGICAL_2",
            "plan": 39,
            "gem_port": 14
        },
        "OZ_SKY_2": {
            "line_profile": 2,
            "srv_profile": 2,
            "vlan": 1102,
            "provider": "VNET",
            "name": "OZ_SKY_2",
            "plan": 45,
            "gem_port": 14
        },
        "OZ_START_2": {
            "line_profile": 2,
            "srv_profile": 2,
            "vlan": 1102,
            "provider": "VNET",
            "name": "OZ_START_2",
            "plan": 23,
            "gem_port": 14
        },
        "OZ_FAMILY_2": {
            "line_profile": 2,
            "srv_profile": 2,
            "vlan": 1102,
            "provider": "VNET",
            "name": "OZ_FAMILY_2",
            "plan": 25,
            "gem_port": 14
        },
        "OZ_EMPRENDE_2": {
            "line_profile": 2,
            "srv_profile": 2,
            "vlan": 1102,
            "provider": "VNET",
            "name": "OZ_EMPRENDE_2",
            "plan": 42,
            "gem_port": 14
        },
        "OZ_CONECTA_2": {
            "line_profile": 2,
            "srv_profile": 2,
            "vlan": 1102,
            "provider": "VNET",
            "name": "OZ_CONECTA_2",
            "plan": 44,
            "gem_port": 14
        },
        "OZ_INICIATE_2": {
            "line_profile": 2,
            "srv_profile": 2,
            "vlan": 1102,
            "provider": "VNET",
            "name": "OZ_INICIATE_2",
            "plan": 43,
            "gem_port": 14
        },
        "OZ_LIFT_2": {
            "line_profile": 2,
            "srv_profile": 2,
            "vlan": 1102,
            "provider": "VNET",
            "name": "OZ_LIFT_2",
            "plan": 6,
            "gem_port": 14
        },
        "OZ_UP_2": {
            "line_profile": 2,
            "srv_profile": 2,
            "vlan": 1102,
            "provider": "VNET",
            "name": "OZ_UP_2",
            "plan": 49,
            "gem_port": 14
        },
        "OZ_PLUS_IP": {
            "line_profile": 4,
            "srv_profile": 2,
            "vlan": 1104,
            "provider": "PUBLICAS",
            "name": "OZ_PLUS_IP",
            "plan": 47,
            "gem_port": 14
        },
        "OZ_MAX_IP": {
            "line_profile": 4,
            "srv_profile": 2,
            "vlan": 1104,
            "provider": "PUBLICAS",
            "name": "OZ_MAX_IP",
            "plan": 46,
            "gem_port": 14
        },
        "OZ_NEXT_IP": {
            "line_profile": 4,
            "srv_profile": 2,
            "vlan": 1104,
            "provider": "PUBLICAS",
            "name": "OZ_NEXT_IP",
            "plan": 40,
            "gem_port": 14
        },
        "OZ_MAGICAL_IP": {
            "line_profile": 4,
            "srv_profile": 2,
            "vlan": 1104,
            "provider": "PUBLICAS",
            "name": "OZ_MAGICAL_IP",
            "plan": 39,
            "gem_port": 14
        },
        "OZ_SKY_IP": {
            "line_profile": 4,
            "srv_profile": 2,
            "vlan": 1104,
            "provider": "PUBLICAS",
            "name": "OZ_SKY_IP",
            "plan": 45,
            "gem_port": 14
        },
        "OZ_START_IP": {
            "line_profile": 4,
            "srv_profile": 2,
            "vlan": 1104,
            "provider": "PUBLICAS",
            "name": "OZ_START_IP",
            "plan": 23,
            "gem_port": 14
        },
        "OZ_FAMILY_IP": {
            "line_profile": 4,
            "srv_profile": 2,
            "vlan": 1104,
            "provider": "PUBLICAS",
            "name": "OZ_FAMILY_IP",
            "plan": 25,
            "gem_port": 14
        },
        "OZ_EMPRENDE_IP": {
            "line_profile": 4,
            "srv_profile": 2,
            "vlan": 1104,
            "provider": "PUBLICAS",
            "name": "OZ_EMPRENDE_IP",
            "plan": 42,
            "gem_port": 14
        },
        "OZ_CONECTA_IP": {
            "line_profile": 4,
            "srv_profile": 2,
            "vlan": 1104,
            "provider": "PUBLICAS",
            "name": "OZ_CONECTA_IP",
            "plan": 44,
            "gem_port": 14
        },
        "OZ_INICIATE_IP": {
            "line_profile": 4,
            "srv_profile": 2,
            "vlan": 1104,
            "provider": "PUBLICAS",
            "name": "OZ_INICIATE_IP",
            "plan": 43,
            "gem_port": 14
        },
        "OZ_LIFT_IP": {
            "line_profile": 4,
            "srv_profile": 2,
            "vlan": 1104,
            "provider": "PUBLICAS",
            "name": "OZ_LIFT_IP",
            "plan": 6,
            "gem_port": 14
        },
        "OZ_UP_IP": {
            "line_profile": 4,
            "srv_profile": 2,
            "vlan": 1104,
            "provider": "PUBLICAS",
            "name": "OZ_UP_IP",
            "plan": 49,
            "gem_port": 14
        },
    },
    "3": {
        "OZ_PLUS_1": {
            "line_profile": 2,
            "srv_profile": 1,
            "vlan": 1101,
            "provider": "INTER",
            "name": "OZ_PLUS_1",
            "plan": 49,
            "gem_port": 14
        },
        "OZ_MAX_1": {
            "line_profile": 2,
            "srv_profile": 1,
            "vlan": 1101,
            "provider": "INTER",
            "name": "OZ_MAX_1",
            "plan": 48,
            "gem_port": 14
        },
        "OZ_NEXT_1": {
            "line_profile": 2,
            "srv_profile": 1,
            "vlan": 1101,
            "provider": "INTER",
            "name": "OZ_NEXT_1",
            "plan": 33,
            "gem_port": 14
        },
        "OZ_MAGICAL_1": {
            "line_profile": 2,
            "srv_profile": 1,
            "vlan": 1101,
            "provider": "INTER",
            "name": "OZ_MAGICAL_1",
            "plan": 32,
            "gem_port": 14
        },
        "OZ_SKY_1": {
            "line_profile": 2,
            "srv_profile": 1,
            "vlan": 1101,
            "provider": "INTER",
            "name": "OZ_SKY_1",
            "plan": 47,
            "gem_port": 14
        },
        "OZ_START_1": {
            "line_profile": 2,
            "srv_profile": 1,
            "vlan": 1101,
            "provider": "INTER",
            "name": "OZ_START_1",
            "plan": 9,
            "gem_port": 14
        },
        "OZ_FAMILY_1": {
            "line_profile": 2,
            "srv_profile": 1,
            "vlan": 1101,
            "provider": "INTER",
            "name": "OZ_FAMILY_1",
            "plan": 15,
            "gem_port": 14
        },
        "OZ_EMPRENDE_1": {
            "line_profile": 2,
            "srv_profile": 1,
            "vlan": 1101,
            "provider": "INTER",
            "name": "OZ_EMPRENDE_1",
            "plan": 44,
            "gem_port": 14
        },
        "OZ_CONECTA_1": {
            "line_profile": 2,
            "srv_profile": 1,
            "vlan": 1101,
            "provider": "INTER",
            "name": "OZ_CONECTA_1",
            "plan": 46,
            "gem_port": 14
        },
        "OZ_INICIATE_1": {
            "line_profile": 2,
            "srv_profile": 1,
            "vlan": 1101,
            "provider": "INTER",
            "name": "OZ_INICIATE_1",
            "plan": 45,
            "gem_port": 14
        },
        "OZ_LIFT_1": {
            "line_profile": 2,
            "srv_profile": 1,
            "vlan": 1101,
            "provider": "INTER",
            "name": "OZ_LIFT_1",
            "plan": 34,
            "gem_port": 14
        },
        "OZ_UP_1": {
            "line_profile": 2,
            "srv_profile": 1,
            "vlan": 1101,
            "provider": "INTER",
            "name": "OZ_UP_1",
            "plan": 36,
            "gem_port": 14
        },
        "OZ_PLUS_2": {
            "line_profile": 2,
            "srv_profile": 1,
            "vlan": 1102,
            "provider": "VNET",
            "name": "OZ_PLUS_2",
            "plan": 49,
            "gem_port": 14
        },
        "OZ_MAX_2": {
            "line_profile": 2,
            "srv_profile": 1,
            "vlan": 1102,
            "provider": "VNET",
            "name": "OZ_MAX_2",
            "plan": 48,
            "gem_port": 14
        },
        "OZ_NEXT_2": {
            "line_profile": 2,
            "srv_profile": 1,
            "vlan": 1102,
            "provider": "VNET",
            "name": "OZ_NEXT_2",
            "plan": 33,
            "gem_port": 14
        },
        "OZ_MAGICAL_2": {
            "line_profile": 2,
            "srv_profile": 1,
            "vlan": 1102,
            "provider": "VNET",
            "name": "OZ_MAGICAL_2",
            "plan": 32,
            "gem_port": 14
        },
        "OZ_SKY_2": {
            "line_profile": 2,
            "srv_profile": 1,
            "vlan": 1102,
            "provider": "VNET",
            "name": "OZ_SKY_2",
            "plan": 47,
            "gem_port": 14
        },
        "OZ_START_2": {
            "line_profile": 2,
            "srv_profile": 1,
            "vlan": 1102,
            "provider": "VNET",
            "name": "OZ_START_2",
            "plan": 9,
            "gem_port": 14
        },
        "OZ_FAMILY_2": {
            "line_profile": 2,
            "srv_profile": 1,
            "vlan": 1102,
            "provider": "VNET",
            "name": "OZ_FAMILY_2",
            "plan": 15,
            "gem_port": 14
        },
        "OZ_EMPRENDE_2": {
            "line_profile": 2,
            "srv_profile": 1,
            "vlan": 1102,
            "provider": "VNET",
            "name": "OZ_EMPRENDE_2",
            "plan": 44,
            "gem_port": 14
        },
        "OZ_CONECTA_2": {
            "line_profile": 2,
            "srv_profile": 1,
            "vlan": 1102,
            "provider": "VNET",
            "name": "OZ_CONECTA_2",
            "plan": 46,
            "gem_port": 14
        },
        "OZ_INICIATE_2": {
            "line_profile": 2,
            "srv_profile": 1,
            "vlan": 1102,
            "provider": "VNET",
            "name": "OZ_INICIATE_2",
            "plan": 45,
            "gem_port": 14
        },
        "OZ_LIFT_2": {
            "line_profile": 2,
            "srv_profile": 1,
            "vlan": 1102,
            "provider": "VNET",
            "name": "OZ_LIFT_2",
            "plan": 34,
            "gem_port": 14
        },
        "OZ_UP_2": {
            "line_profile": 2,
            "srv_profile": 1,
            "vlan": 1102,
            "provider": "VNET",
            "name": "OZ_UP_2",
            "plan": 36,
            "gem_port": 14
        },
        "OZ_PLUS_IP": {
            "line_profile": 5,
            "srv_profile": 1,
            "vlan": 1104,
            "provider": "PUBLICAS",
            "name": "OZ_PLUS_IP",
            "plan": 49,
            "gem_port": 14
        },
        "OZ_MAX_IP": {
            "line_profile": 5,
            "srv_profile": 1,
            "vlan": 1104,
            "provider": "PUBLICAS",
            "name": "OZ_MAX_IP",
            "plan": 48,
            "gem_port": 14
        },
        "OZ_NEXT_IP": {
            "line_profile": 5,
            "srv_profile": 1,
            "vlan": 1104,
            "provider": "PUBLICAS",
            "name": "OZ_NEXT_IP",
            "plan": 33,
            "gem_port": 14
        },
        "OZ_MAGICAL_IP": {
            "line_profile": 5,
            "srv_profile": 1,
            "vlan": 1104,
            "provider": "PUBLICAS",
            "name": "OZ_MAGICAL_IP",
            "plan": 32,
            "gem_port": 14
        },
        "OZ_SKY_IP": {
            "line_profile": 5,
            "srv_profile": 1,
            "vlan": 1104,
            "provider": "PUBLICAS",
            "name": "OZ_SKY_IP",
            "plan": 47,
            "gem_port": 14
        },
        "OZ_START_IP": {
            "line_profile": 5,
            "srv_profile": 1,
            "vlan": 1104,
            "provider": "PUBLICAS",
            "name": "OZ_START_IP",
            "plan": 9,
            "gem_port": 14
        },
        "OZ_FAMILY_IP": {
            "line_profile": 5,
            "srv_profile": 1,
            "vlan": 1104,
            "provider": "PUBLICAS",
            "name": "OZ_FAMILY_IP",
            "plan": 15,
            "gem_port": 14
        },
        "OZ_EMPRENDE_IP": {
            "line_profile": 5,
            "srv_profile": 1,
            "vlan": 1104,
            "provider": "PUBLICAS",
            "name": "OZ_EMPRENDE_IP",
            "plan": 44,
            "gem_port": 14
        },
        "OZ_CONECTA_IP": {
            "line_profile": 5,
            "srv_profile": 1,
            "vlan": 1104,
            "provider": "PUBLICAS",
            "name": "OZ_CONECTA_IP",
            "plan": 46,
            "gem_port": 14
        },
        "OZ_INICIATE_IP": {
            "line_profile": 5,
            "srv_profile": 1,
            "vlan": 1104,
            "provider": "PUBLICAS",
            "name": "OZ_INICIATE_IP",
            "plan": 45,
            "gem_port": 14
        },
        "OZ_LIFT_IP": {
            "line_profile": 5,
            "srv_profile": 1,
            "vlan": 1104,
            "provider": "PUBLICAS",
            "name": "OZ_LIFT_IP",
            "plan": 34,
            "gem_port": 14
        },
        "OZ_UP_IP": {
            "line_profile": 5,
            "srv_profile": 1,
            "vlan": 1104,
            "provider": "PUBLICAS",
            "name": "OZ_UP_IP",
            "plan": 36,
            "gem_port": 14
        },
    }
}
###########	OLD      ###########


###########			IP MIGRATIONS    		 ###########
# PLANS = {
#         "OZ_0_1": {
#             "line_profile": 3,
#             "srv_profile": 210,
#             "vlan": 3100,
#             "provider": "INTER",
#             "name": "OZ_0_1",
#             "plan": 210,
#             "gem_port": 20
#         },
#         "OZ_PLUS_1": {
#             "line_profile": 17,
#             "srv_profile": 211,
#             "vlan": 3101,
#             "name": "OZ_PLUS_1",
#             "provider": "INTER",
#             "plan": 211,
#             "gem_port": 21
#         },
#         "OZ_MAX_1": {
#             "line_profile": 27,
#             "srv_profile": 212,
#             "vlan": 3102,
#             "name": "OZ_MAX_1",
#             "provider": "INTER",
#             "plan": 212,
#             "gem_port": 22
#         },
#         "OZ_NEXT_1": {
#             "line_profile": 37,
#             "srv_profile": 213,
#             "vlan": 3103,
#             "name": "OZ_NEXT_1",
#             "provider": "INTER",
#             "plan": 213,
#             "gem_port": 23
#         },
#         "OZ_MAGICAL_1": {
#             "line_profile": 47,
#             "srv_profile": 214,
#             "vlan": 3104,
#             "name": "OZ_MAGICAL_1",
#             "provider": "INTER",
#             "plan": 214,
#             "gem_port": 24
#         },
#         "OZ_SKY_1": {
#             "line_profile": 57,
#             "srv_profile": 215,
#             "vlan": 3105,
#             "name": "OZ_SKY_1",
#             "provider": "INTER",
#             "plan": 215,
#             "gem_port": 25
#         },
#         "OZ_0_2": {
#             "line_profile": 3,
#             "srv_profile": 210,
#             "vlan": 2100,
#             "provider": "VNET",
#             "name": "OZ_0_2",
#             "plan": 210,
#             "gem_port": 20
#         },
#         "OZ_PLUS_2": {
#             "line_profile": 17,
#             "srv_profile": 211,
#             "vlan": 2101,
#             "name": "OZ_PLUS_2",
#             "provider": "VNET",
#             "plan": 211,
#             "gem_port": 21
#         },
#         "OZ_MAX_2": {
#             "line_profile": 27,
#             "srv_profile": 212,
#             "vlan": 2102,
#             "name": "OZ_MAX_2",
#             "provider": "VNET",
#             "plan": 212,
#             "gem_port": 22
#         },
#         "OZ_NEXT_2": {
#             "line_profile": 37,
#             "srv_profile": 213,
#             "vlan": 2103,
#             "name": "OZ_NEXT_2",
#             "provider": "VNET",
#             "plan": 213,
#             "gem_port": 23
#         },
#         "OZ_MAGICAL_2": {
#             "line_profile": 47,
#             "srv_profile": 214,
#             "vlan": 2104,
#             "name": "OZ_MAGICAL_2",
#             "provider": "VNET",
#             "plan": 214,
#             "gem_port": 24
#         },
#         "OZ_SKY_2": {
#             "line_profile": 57,
#             "srv_profile": 215,
#             "vlan": 2105,
#             "name": "OZ_SKY_2",
#             "provider": "VNET",
#             "plan": 215,
#             "gem_port": 25
#         },
#         "OZ_PLUS_IP": {
#             "line_profile": 18,
#             "srv_profile": 311,
#             "vlan": 102,
#             "provider": "PUBLICAS",
#             "name": "OZ_PLUS_IP",
#             "plan": 311,
#             "gem_port": 14
#         },
#         "OZ_MAX_IP": {
#             "line_profile": 28,
#             "srv_profile": 312,
#             "vlan": 102,
#             "provider": "PUBLICAS",
#             "name": "OZ_MAX_IP",
#             "plan": 312,
#             "gem_port": 14
#         },
#         "OZ_NEXT_IP": {
#             "line_profile": 38,
#             "srv_profile": 313,
#             "vlan": 102,
#             "provider": "PUBLICAS",
#             "name": "OZ_NEXT_IP",
#             "plan": 313,
#             "gem_port": 14
#         },
#         "OZ_MAGICAL_IP": {
#             "line_profile": 48,
#             "srv_profile": 314,
#             "vlan": 102,
#             "provider": "PUBLICAS",
#             "name": "OZ_MAGICAL_IP",
#             "plan": 314,
#             "gem_port": 14
#         },
#         "OZ_SKY_IP": {
#             "line_profile": 58,
#             "srv_profile": 315,
#             "vlan": 102,
#             "provider": "PUBLICAS",
#             "name": "OZ_SKY_IP",
#             "plan": 315,
#             "gem_port": 14
#         },
# }
###########			IP MIGRATIONS    		 ###########

table = {
    "condition_summary": "------------------------------------------------------------------------------",
    "condition_port": "-----------------------------------------------------------------------------",
    "options_summary": [
        {
            "name": "state",
            "start": 2,
            "end": 3,
            "header": ",onu_id,state,up_date,up_time,down_date,down_time,down_cause_1,down_cause_2,down_cause_3,down_cause_4,down_cause_5,down_cause_6,down_cause_7,down_cause_8",
        },
        {
            "name": "names",
            "start": 4,
            "end": 5,
            "header": ",onu_id,sn,device,distance,rx_tx_power,name1,name2,name3,name4,name5,name6,name7,name8,name9,name10",
        },
    ],
    "options_port": [
        {
            "name": "state",
            "start": 7,
            "end": 8,
            "header": ",f,/s/p,onu_id,sn,control_flag,run_state,config_state,match_state,protect_side,na",
            "header_1": ",f/s/p,onu_id,sn,control_flag,run_state,config_state,match_state,protect_side,na",
        },
        {
            "name": "names",
            "start": 9,
            "end": 10,
            "header": ",f,/s/p,onu_id,name1,name2,name3,name4,name5,name6,name7,name8,name9,name10,name11,name12,name13,name14,name15,name16,name17,name18,name19,name20,name21",
            "header_1": ",f/s/p,onu_id,name1,name2,name3,name4,name5,name6,name7,name8,name9,name10,name11,name12,name13,name14,name15,name16,name17,name18,name19,name20,name21",
        },
    ],
}

ports = {
    "olt": {
        "1": [
            {"fsp": "0/1/0"},
            {"fsp": "0/1/1"},
            {"fsp": "0/1/2"},
            {"fsp": "0/1/3"},
            {"fsp": "0/1/4"},
            {"fsp": "0/1/5"},
            #{"fsp": "0/1/6"},
            #{"fsp": "0/1/7"},
            {"fsp": "0/1/8"},
            #{"fsp": "0/1/9"},
            {"fsp": "0/1/10"},
            {"fsp": "0/1/11"},
            #{"fsp": "0/1/12"},
            {"fsp": "0/1/13"},
            {"fsp": "0/1/14"},
            {"fsp": "0/1/15"},
            {"fsp": "0/2/0"},
            {"fsp": "0/2/1"},
            {"fsp": "0/2/2"},
            #{"fsp": "0/2/3"},
            #{"fsp": "0/2/4"},
            {"fsp": "0/2/5"},
            #{"fsp": "0/2/6"},
            {"fsp": "0/2/7"},
            {"fsp": "0/2/8"},
            #{"fsp": "0/2/9"},
            {"fsp": "0/2/10"},
            {"fsp": "0/2/11"},
            {"fsp": "0/2/12"},
            {"fsp": "0/2/13"},
            #{"fsp": "0/2/14"},
            {"fsp": "0/2/15"},
            {"fsp": "0/3/0"},
            {"fsp": "0/3/1"},
            #{"fsp": "0/3/2"},
            #{"fsp": "0/3/3"},
            {"fsp": "0/3/4"},
            # {"fsp": "0/3/5"},
            {"fsp": "0/3/6"},
            # {"fsp": "0/3/7"},
            {"fsp": "0/3/8"},
            {"fsp": "0/3/9"},
            {"fsp": "0/3/10"},
            {"fsp": "0/3/11"},
            {"fsp": "0/3/12"},
            # {"fsp": "0/3/13"},
            # {"fsp": "0/3/14"},
            {"fsp": "0/3/15"},
            {"fsp": "0/4/0"},
            {"fsp": "0/4/1"},
            {"fsp": "0/4/2"},
            {"fsp": "0/4/3"},
            {"fsp": "0/4/4"},
            {"fsp": "0/4/5"},
            {"fsp": "0/4/6"},
            {"fsp": "0/4/7"},
            {"fsp": "0/4/8"},
            {"fsp": "0/4/9"},
            {"fsp": "0/4/10"},
            # {"fsp": "0/4/11"},
            {"fsp": "0/4/12"},
            {"fsp": "0/4/13"},
            {"fsp": "0/4/14"},
            {"fsp": "0/4/15"},
            {"fsp": "0/5/0"},
            {"fsp": "0/5/1"},
            {"fsp": "0/5/2"},
            # {"fsp": "0/5/3"},
            {"fsp": "0/5/4"},
            {"fsp": "0/5/5"},
            # {"fsp": "0/5/6"},
            {"fsp": "0/5/7"},
            {"fsp": "0/5/8"},
            {"fsp": "0/5/9"},
            {"fsp": "0/5/10"},
            {"fsp": "0/5/11"},
            {"fsp": "0/5/12"},
            # {"fsp": "0/5/13"},
            {"fsp": "0/5/14"},
            # {"fsp": "0/5/15"},
            {"fsp": "0/6/0"},
            {"fsp": "0/6/1"},
            {"fsp": "0/6/2"},
            {"fsp": "0/6/3"},
            {"fsp": "0/6/4"},
            {"fsp": "0/6/5"},
            {"fsp": "0/6/6"},
            {"fsp": "0/6/7"},
            {"fsp": "0/6/8"},
            {"fsp": "0/6/9"},
            {"fsp": "0/6/10"},
            {"fsp": "0/6/11"},
            {"fsp": "0/6/12"},
            {"fsp": "0/6/13"},
            {"fsp": "0/6/14"},
            {"fsp": "0/6/15"},
            {"fsp": "0/7/0"},
            {"fsp": "0/7/1"},
            {"fsp": "0/7/2"},
            {"fsp": "0/7/3"},
            {"fsp": "0/7/4"},
            {"fsp": "0/7/5"},
            {"fsp": "0/7/6"},
            {"fsp": "0/7/7"},
            {"fsp": "0/7/8"},
            {"fsp": "0/7/9"},
            {"fsp": "0/7/10"},
            {"fsp": "0/7/11"},
            {"fsp": "0/7/12"},
            {"fsp": "0/7/13"},
            {"fsp": "0/7/14"},
            {"fsp": "0/7/15"},
            {"fsp": "0/10/0"},
            {"fsp": "0/10/1"},
            {"fsp": "0/10/2"},
            {"fsp": "0/10/3"},
            {"fsp": "0/10/4"},
            {"fsp": "0/10/5"},
            {"fsp": "0/10/6"},
            {"fsp": "0/10/7"},
            {"fsp": "0/10/8"},
            {"fsp": "0/10/9"},
            {"fsp": "0/10/10"},
            {"fsp": "0/10/11"},
            {"fsp": "0/10/12"},
            {"fsp": "0/10/13"},
            {"fsp": "0/10/14"},
            {"fsp": "0/10/15"},
        ],
        "2": [
            {"fsp": "0/1/6"},
            {"fsp": "0/1/7"},
            {"fsp": "0/1/9"},
            {"fsp": "0/1/12"},
            {"fsp": "0/2/3"},
            {"fsp": "0/2/4"},
            {"fsp": "0/2/6"},
            {"fsp": "0/2/9"},
            {"fsp": "0/2/14"},
            {"fsp": "0/3/2"},
            {"fsp": "0/3/3"},
            {"fsp": "0/3/5"},
            {"fsp": "0/3/7"},
            {"fsp": "0/3/13"},
            {"fsp": "0/3/14"},
        ],
        "3": [
            {"fsp": "0/1/11"},
            {"fsp": "0/2/3"},
            {"fsp": "0/2/6"},
            {"fsp": "0/2/13"},
            {"fsp": "0/2/15"},
        ],
    },
    "count": {
        "1": {
            "0/1/0": 0,
            "0/1/1": 0,
            "0/1/2": 0,
            "0/1/3": 0,
            "0/1/4": 0,
            "0/1/5": 0,
            #"0/1/6": 0,
            #"0/1/7": 0,
            "0/1/8": 0,
            #"0/1/9": 0,
            "0/1/10": 0,
            "0/1/11": 0,
            #"0/1/12": 0,
            "0/1/13": 0,
            "0/1/14": 0,
            "0/1/15": 0,
            "0/2/0": 0,
            "0/2/1": 0,
            "0/2/2": 0,
            #"0/2/3": 0,
            #"0/2/4": 0,
            "0/2/5": 0,
            #"0/2/6": 0,
            "0/2/7": 0,
            "0/2/8": 0,
            #"0/2/9": 0,
            "0/2/10": 0,
            "0/2/11": 0,
            "0/2/12": 0,
            "0/2/13": 0,
            #"0/2/14": 0,
            "0/2/15": 0,
            "0/3/0": 0,
            "0/3/1": 0,
            #"0/3/2": 0,
            #"0/3/3": 0,
            "0/3/4": 0,
            #"0/3/5": 0,
            "0/3/6": 0,
            #"0/3/7": 0,
            "0/3/8": 0,
            "0/3/9": 0,
            "0/3/10": 0,
            "0/3/11": 0,
            "0/3/12": 0,
            #"0/3/13": 0,
            #"0/3/14": 0,
            "0/3/15": 0,
            "0/4/0": 0,
            "0/4/1": 0,
            "0/4/2": 0,
            "0/4/3": 0,
            "0/4/4": 0,
            "0/4/5": 0,
            "0/4/6": 0,
            "0/4/7": 0,
            "0/4/8": 0,
            "0/4/9": 0,
            "0/4/10": 0,
            #"0/4/11": 0,
            "0/4/12": 0,
            "0/4/13": 0,
            "0/4/14": 0,
            "0/4/15": 0,
            "0/5/0": 0,
            "0/5/1": 0,
            "0/5/2": 0,
            "0/5/3": 0,
            "0/5/4": 0,
            "0/5/5": 0,
            "0/5/6": 0,
            "0/5/7": 0,
            "0/5/8": 0,
            "0/5/9": 0,
            "0/5/10": 0,
            "0/5/11": 0,
            "0/5/12": 0,
            "0/5/13": 0,
            "0/5/14": 0,
            "0/5/15": 0,
            "0/6/0": 0,
            "0/6/1": 0,
            "0/6/2": 0,
            "0/6/3": 0,
            "0/6/4": 0,
            "0/6/5": 0,
            "0/6/6": 0,
            "0/6/7": 0,
            "0/6/8": 0,
            "0/6/9": 0,
            "0/6/10": 0,
            "0/6/11": 0,
            "0/6/12": 0,
            "0/6/13": 0,
            "0/6/14": 0,
            "0/6/15": 0,
            "0/7/0": 0,
            "0/7/1": 0,
            "0/7/2": 0,
            "0/7/3": 0,
            "0/7/4": 0,
            "0/7/5": 0,
            "0/7/6": 0,
            "0/7/7": 0,
            "0/7/8": 0,
            "0/7/9": 0,
            "0/7/10": 0,
            "0/7/11": 0,
            "0/7/12": 0,
            "0/7/13": 0,
            "0/7/14": 0,
            "0/7/15": 0,
            "0/10/0": 0,
            "0/10/1": 0,
            "0/10/2": 0,
            "0/10/3": 0,
            "0/10/4": 0,
            "0/10/5": 0,
            "0/10/6": 0,
            "0/10/7": 0,
            "0/10/8": 0,
            "0/10/9": 0,
            "0/10/10": 0,
            "0/10/11": 0,
            "0/10/12": 0,
            "0/10/13": 0,
            "0/10/14": 0,
            "0/10/15": 0,
        },
        "2": {
            "0/1/6": 0,
            "0/1/7": 0,
            "0/1/9": 0,
            "0/1/12": 0,
            "0/2/3": 0,
            "0/2/4": 0,
            "0/2/6": 0,
            "0/2/9": 0,
            "0/2/14": 0,
            "0/3/2": 0,
            "0/3/3": 0,
            "0/3/5": 0,
            "0/3/7": 0,
            "0/3/13": 0,
            "0/3/14": 0,
        },
        "3": {
            "0/1/11": 0,
            "0/2/3": 0,
            "0/2/6": 0,
            "0/2/13": 0,
            "0/2/15": 0,
        },
    },
}

speed = {
    "up": "Up traffic \(kbps\)          : ",
    "down": "Down traffic \(kbps\)        : ",
    "cond": "----------------------------------------------------------------",
}

interface = {
    "start":"InUti/OutUti: input utility/output utility",
    "end":"NULL0",
    "header":"Interface,PHY,Protocol,InUti,OutUti,inErrors,outErrors\n",
}

rtrConflicts = {
    "condition": "---------------------------------------------------------------------------------------",
    "headerConf": "NA,ID,start,end,total,used,idle,conflict,disable,reserved,staticBind",
    "headerSect": "ip,mac,userId,lease,status,index,na"
}

wanMapper = {
    "1": {
        "2100": "2",
        "2101": "2",
        "2102": "2",
        "2102": "2",
        "2103": "2",
        "2104": "2",
        "2105": "2",
        "3100": "1",
        "3101": "1",
        "3102": "1",
        "3102": "1",
        "3103": "1",
        "3104": "1",
        "3105": "1",
        "102": "IP"
    },
    "2": {
        "101":"VOIP",
        "1101": "1",
        "1102": "2",
        "1104": "IP",
    },
    "3": {
        "101":"VOIP",
        "1101": "1",
        "1102": "2",
        "1104": "IP",
    },
}

clientData = {
    "fail": None,
    "name": None,
    "olt": None,
    "frame": None,
    "slot": None,
    "port": None,
    "onu_id": None,
    "sn": None,
    "last_down_cause": None,
    "state": None,
    "status": None,
    "type": None,
    "ip_address": None,
    "plan_name": None,
    "wan": [{"spid": None, "vlan": None, "plan": None, "provider": None, "plan_name": None, "state": None}],
    "temp": None,
    "pwr": None,
    "line_profile": None,
    "srv_profile": None,
    "device": None,
}

providerMap = {"1101": "INTER", "1102": "VNET",
               "1104": "IP PUBLICAS", "101": "VOIP"}
